=== jiankangren/tms-sim/devdoc/genericserialisation.xsd
<?xml version="1.0"?>


<xs:schema  xmlns:xs="http://www.w3.org/2001/XMLSchema"
targetNamespace="http://www.tmsxmlns.com"
xmlns="http://www.tmsxmlns.com"
elementFormDefault="qualified" >

  <xs:complexType name="fileType">
    <xs:sequence>
      <xs:element name="type" type="xs:string" />
      <xs:element name="object" type="objectType"/>
    </xs:sequence>
  </xs:complexType>
  
  <!--<xs:element name="object" type="objectType" />-->


  <xs:complexType name="objectType">
    <xs:choice minOccurs="1" maxOccurs="unbounded">

      <xs:element name="int">
	<xs:complexType>
	  <xs:simpleContent>
	    <xs:extension base="xs:int">
	      <xs:attribute name="name" type="xs:string" use="required" />
	    </xs:extension>
	  </xs:simpleContent>
	</xs:complexType>
      </xs:element>

      <xs:element name="string">
	<xs:complexType>
	  <xs:simpleContent>
	    <xs:extension base="xs:string">
	      <xs:attribute name="name" type="xs:string" use="required" />
	    </xs:extension>
	  </xs:simpleContent>
	</xs:complexType>
      </xs:element>

      <xs:element name="float">
	<xs:complexType>
	  <xs:simpleContent>
	    <xs:extension base="xs:float">
	      <xs:attribute name="name" type="xs:string" use="required" />
	    </xs:extension>
	  </xs:simpleContent>
	</xs:complexType>
      </xs:element>

      <xs:element name="object" type="objectType">
	<!--<xs:complexType>
	  <xs:complexContent>
	    <xs:extension base="objectType">
	      <xs:attribute name="name" type="xs:string" use="required" />
	    </xs:extension>
	  </xs:complexContent>
	</xs:complexType>-->
      </xs:element>

    </xs:choice>
    <xs:attribute name="name" type="xs:string" use="required" />
  </xs:complexType>

  <xs:element name="file" type="fileType" />
</xs:schema>

=== jiankangren/tms-sim/devdoc/ex-serialisation.xml
<?xml version="1.0"?>

<file xmlns="http://www.tmsxmlns.com"
      xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
      xsi:schemaLocation="http://www.tmsxmlns.com genericserialisation.xsd">
  <type>some type</type>
  <object name="foo"> 
    
    <int name="int1">42</int>
    <int name="int2">43</int>
    <float name="float1">1.92</float>
    
    <object name="bar">
      <string name="name">yao</string>
      <int name="id">21</int>
    </object>

  </object>
</file>
