=== jiankangren/tms-sim/tasksets/taskset.xsd
<?xml version="1.0"?>

<!-- Valid after: http://www.w3.org/2001/03/webdata/xsv -->

<xs:schema  xmlns:xs="http://www.w3.org/2001/XMLSchema"
            targetNamespace="http://www.tmsxmlns.com"
            xmlns="http://www.tmsxmlns.com"
            elementFormDefault="qualified" >


  <xs:complexType name="uaexptype">
    <xs:sequence>
      <xs:element name="weight" type="xs:string" default="0.5"/>
    </xs:sequence>
  </xs:complexType>
  
  <xs:complexType name="uawindowtype">
    <xs:sequence>
      <xs:element name="size" type="xs:string" default="1"/>
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="tasksettype">
    <xs:sequence>
      <xs:choice minOccurs="0" maxOccurs="unbounded">
          <xs:element name="periodictask" type="periodictasktype" />
          <xs:element name="sporadictask" type="sporadictasktype" />
          <xs:element name="mktask" type="mktasktype" />
          <xs:element name="mkctask" type="mkctasktype" />
          <xs:element name="dbptask" type="dbptasktype" />
          <xs:element name="sporadicperiodictask" type="sporadicperiodictasktype" />
          <xs:element name="pproducertask" type="pproducertasktype" />
          <xs:element name="pconsumertask" type="pconsumertasktype" />
      </xs:choice>
    </xs:sequence>
  </xs:complexType>
       
  <xs:complexType name="tasktype">
    <xs:sequence>
      <xs:element name="id" type="xs:nonNegativeInteger"/>
      <xs:element name="executiontime" type="xs:integer"/>
      <xs:element name="criticaltime" type="xs:integer"/>
      
	  <xs:choice>
		<xs:element name="ucfirmrt" type="xs:string"/>
	    <xs:element name="ucnone" type="xs:string"/>
	  </xs:choice>
	  
      <xs:choice>
          <xs:element name="uanone" type="xs:string" />
          <xs:element name="uaexp" type="uaexptype" />
          <xs:element name="uamean" type="xs:string" />
          <xs:element name="uawmean" type="uawindowtype" />
          <xs:element name="uawmk" type="uawmktype" />
      </xs:choice>
      
      <xs:element name="priority" type="xs:nonNegativeInteger"/>
      
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="uawmktype">
    <xs:sequence>
      <xs:element name="m" type="xs:nonNegativeInteger"/>
      <xs:element name="k" type="xs:nonNegativeInteger"/>
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="sporadictasktype">
    <xs:complexContent>
      <xs:extension base="tasktype">
        <xs:sequence>
        
          <xs:element name="minperiod" type="xs:string"/>
          <xs:element name="seed" type="xs:string" default="0.5"/>
          <xs:element name="probability" type="xs:decimal"/>
          <xs:element name="offset" type="xs:integer" default="0"/>
        
        </xs:sequence>
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>
  
  <xs:complexType name="periodictasktype">
    <xs:complexContent>
      <xs:extension base="tasktype">
        <xs:sequence>
           <xs:element name="period" type="xs:integer" />
           <xs:element name="offset" type="xs:integer" default="0"/>
        </xs:sequence>
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>
  
  <xs:complexType name="pproducertasktype">
    <xs:complexContent>
      <xs:extension base="periodictasktype">
        <xs:sequence>
	  <xs:element name="buffersize" type="xs:integer" />
          <xs:element name="responsetime" type="xs:integer" />
        
        </xs:sequence>
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>

  <xs:complexType name="producerlisttype">
    <xs:sequence>
      <xs:choice minOccurs="1" maxOccurs="unbounded">
	<xs:element name="producer" type="xs:string" />
      </xs:choice>
    </xs:sequence>
  </xs:complexType>
  
  <xs:complexType name="pconsumertasktype">
    <xs:complexContent>
      <xs:extension base="periodictasktype">
        <xs:sequence>
       
          <xs:element name="responsetime" type="xs:integer" />
	  <xs:element name="producers" type="producerlisttype" minOccurs="0" maxOccurs="1" />
        </xs:sequence>
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>
  
  <xs:complexType name="mktasktype">
    <xs:complexContent>
      <xs:extension base="periodictasktype">
        <xs:sequence>
          <xs:element name="m" type="xs:integer" />
          <xs:element name="k" type="xs:integer" />
          <xs:element name="spin" type="xs:integer" />
	  <xs:element name="mkstate" type="xs:string" default="1111111111111111111111111111111111111111111111111111111111111111" minOccurs="0" maxOccurs="1"/>
        </xs:sequence>
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>

  <xs:complexType name="mkctasktype">
    <xs:complexContent>
      <xs:extension base="mktasktype">
        <xs:sequence>
        
        </xs:sequence>
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>

  <xs:complexType name="dbptasktype">
    <xs:complexContent>
      <xs:extension base="mktasktype">
        <xs:sequence>
        
        </xs:sequence>
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>
  
  <xs:complexType name="sporadicperiodictasktype">
    <xs:complexContent>
      <xs:extension base="tasktype">
        <xs:sequence>
        
           <xs:element name="period" type="xs:integer" />
           <xs:element name="offset" type="xs:integer" default="0"/>
           <xs:element name="seed" type="xs:string" default="0.5"/>
          <xs:element name="probability" type="xs:decimal"/>
          
        </xs:sequence>
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>

  <xs:element name="taskset" type="tasksettype"/>

</xs:schema>

=== jiankangren/tms-sim/tasksets/taskset7.xml
<?xml version="1.0"?>

<!-- 
good-natured task set with full utilisation through periodic tasks

PeriodicTask t7p1(1, 6, 2, 6, new UCAL, new UAGR, 0);
PeriodicTask t7p2(2, 8, 2, 8, new UCAL, new UAGR, 2);
PeriodicTask t7p3(3, 12, 3, 12, new UCAL, new UAGR, 4);
PeriodicTask t7p4(4, 6, 1, 6, new UCAL, new UAGR, 5);

SporadicTask t7s1(11, 13, 1, 0xcafe600d, 5, new UCAL, new UAGR, 0.33);
SporadicTask t7s2(11, 19, 1, 0xbadcafe0, 5, new UCAL, new UAGR, 0.33);
-->

<taskset
  xmlns="http://www.tmsxmlns.com"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://www.tmsxmlns.com taskset.xsd">

  <periodictask>
    <id>1</id>
    <executiontime>2</executiontime>
    <criticaltime>6</criticaltime>
    <ucfirmrt></ucfirmrt>
    <uaexp>
    	<weight>0.5</weight>
    </uaexp>
    <priority>0</priority>
    <period>6</period>
    <offset>0</offset>
  </periodictask>
 
  <periodictask>
    <id>2</id>
    <executiontime>2</executiontime>
    <criticaltime>8</criticaltime>
    <ucfirmrt></ucfirmrt>
    <uaexp>
    	<weight>0.5</weight>
    </uaexp>
    <priority>2</priority>
    <period>8</period>
    <offset>0</offset>
  </periodictask>
  
  <periodictask>
    <id>3</id>
    <executiontime>3</executiontime>
    <criticaltime>12</criticaltime>
    <ucfirmrt></ucfirmrt>
    <uaexp>
    	<weight>0.5</weight>
    </uaexp>
    <priority>4</priority>
    <period>12</period>
    <offset>0</offset>
  </periodictask>
  
  <periodictask>
    <id>4</id>
    <executiontime>1</executiontime>
    <criticaltime>6</criticaltime>
    <ucfirmrt></ucfirmrt>
    <uaexp>
    	<weight>0.5</weight>
    </uaexp>
    <priority>5</priority>
    <period>6</period>
    <offset>0</offset>
  </periodictask>
  
  <sporadictask>
    <id>11</id>
    <executiontime>1</executiontime>
    <criticaltime>5</criticaltime>
    <ucfirmrt></ucfirmrt>
    <uaexp>
		<weight>0.5</weight>
    </uaexp>
    <priority>1</priority>
    <minperiod>13</minperiod>
    <seed>0xcafe600d</seed>
    <probability>0.33</probability>
    <offset>0</offset>   
  </sporadictask>
  
  <sporadictask>
    <id>12</id>
    <executiontime>1</executiontime>
    <criticaltime>5</criticaltime>
    <ucfirmrt></ucfirmrt>
    <uaexp>
		<weight>0.5</weight>
    </uaexp>
    <priority>1</priority>
    <minperiod>19</minperiod>
    <seed>0xbadcafe0</seed>
    <probability>0.33</probability>
    <offset>0</offset>   
  </sporadictask>
  
</taskset>

=== jiankangren/tms-sim/tasksets/taskset11.xml
<?xml version="1.0"?>

<!-- 

overloaded task set from (m,k)-firm overload paper [ramanathan99pds] (TS11)

PeriodicTask t11p1(1,  3, 1,  3, new UCAL, new UAGR, 0);
PeriodicTask t11p2(2,  4, 2,  4, new UCAL, new UAGR, 0);
PeriodicTask t11p3(3, 12, 3, 21, new UCAL, new UAGR, 0);
-->

<taskset
  xmlns="http://www.tmsxmlns.com"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://www.tmsxmlns.com taskset.xsd">

  <periodictask>
    <id>1</id>
    <executiontime>1</executiontime>
    <criticaltime>3</criticaltime>
    <ucfirmrt></ucfirmrt>
    <uaexp>
    	<weight>0.5</weight>
    </uaexp>
    <priority>0</priority>
    <period>3</period>
    <offset>0</offset>
  </periodictask>
 
  <periodictask>
    <id>2</id>
    <executiontime>2</executiontime>
    <criticaltime>4</criticaltime>
    <ucfirmrt></ucfirmrt>
    <uaexp>
    	<weight>0.5</weight>
    </uaexp>
    <priority>0</priority>
    <period>4</period>
    <offset>0</offset>
  </periodictask>
  
  <periodictask>
    <id>3</id>
    <executiontime>3</executiontime>
    <criticaltime>21</criticaltime>
    <ucfirmrt></ucfirmrt>
    <uaexp>
    	<weight>0.5</weight>
    </uaexp>
    <priority>0</priority>
    <period>12</period>
    <offset>0</offset>
  </periodictask> 
  
</taskset>

=== jiankangren/tms-sim/tasksets/taskset_out.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--Hier kommen die Tasks-->
<taskset xmlns="http://www.tmsxmlns.com" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.tmsxmlns.com taskset.xsd">

  <periodictask>
    <id>1</id>
    <executiontime>4</executiontime>
    <criticaltime>4</criticaltime>
    <ucfirmrt/>
    <uamean/>
    <priority>1</priority>
    <period>7</period>
    <offset>1</offset>
  </periodictask>


  <periodictask>
    <id>2</id>
    <executiontime>3</executiontime>
    <criticaltime>3</criticaltime>
    <ucfirmrt/>
    <uamean/>
    <priority>1</priority>
    <period>16</period>
    <offset>1</offset>
  </periodictask>


  <periodictask>
    <id>3</id>
    <executiontime>4</executiontime>
    <criticaltime>4</criticaltime>
    <ucfirmrt/>
    <uamean/>
    <priority>1</priority>
    <period>16</period>
    <offset>1</offset>
  </periodictask>


  <periodictask>
    <id>4</id>
    <executiontime>2</executiontime>
    <criticaltime>2</criticaltime>
    <ucfirmrt/>
    <uamean/>
    <priority>1</priority>
    <period>13</period>
    <offset>1</offset>
  </periodictask>


  <periodictask>
    <id>5</id>
    <executiontime>5</executiontime>
    <criticaltime>5</criticaltime>
    <ucfirmrt/>
    <uamean/>
    <priority>1</priority>
    <period>2</period>
    <offset>1</offset>
  </periodictask>


  <periodictask>
    <id>6</id>
    <executiontime>3</executiontime>
    <criticaltime>3</criticaltime>
    <ucfirmrt/>
    <uamean/>
    <priority>1</priority>
    <period>8</period>
    <offset>1</offset>
  </periodictask>


  <periodictask>
    <id>7</id>
    <executiontime>1</executiontime>
    <criticaltime>1</criticaltime>
    <ucfirmrt/>
    <uamean/>
    <priority>1</priority>
    <period>20</period>
    <offset>1</offset>
  </periodictask>


  <periodictask>
    <id>8</id>
    <executiontime>4</executiontime>
    <criticaltime>4</criticaltime>
    <ucfirmrt/>
    <uamean/>
    <priority>1</priority>
    <period>7</period>
    <offset>1</offset>
  </periodictask>


  <periodictask>
    <id>9</id>
    <executiontime>1</executiontime>
    <criticaltime>1</criticaltime>
    <ucfirmrt/>
    <uamean/>
    <priority>1</priority>
    <period>7</period>
    <offset>1</offset>
  </periodictask>


  <periodictask>
    <id>10</id>
    <executiontime>3</executiontime>
    <criticaltime>3</criticaltime>
    <ucfirmrt/>
    <uamean/>
    <priority>1</priority>
    <period>17</period>
    <offset>1</offset>
  </periodictask>


  <sporadictask>
    <id>11</id>
    <executiontime>2</executiontime>
    <criticaltime>9</criticaltime>
    <ucfirmrt/>
    <uamean/>
    <priority>1</priority>
    <minperiod>9</minperiod>
    <seed>0x3e8</seed>
    <probability>0.5</probability>
    <offset>0</offset>
  </sporadictask>


  <sporadictask>
    <id>12</id>
    <executiontime>3</executiontime>
    <criticaltime>10</criticaltime>
    <ucfirmrt/>
    <uamean/>
    <priority>1</priority>
    <minperiod>10</minperiod>
    <seed>0x3e8</seed>
    <probability>0.5</probability>
    <offset>0</offset>
  </sporadictask>


  <sporadictask>
    <id>13</id>
    <executiontime>3</executiontime>
    <criticaltime>11</criticaltime>
    <ucfirmrt/>
    <uamean/>
    <priority>1</priority>
    <minperiod>11</minperiod>
    <seed>0x3e8</seed>
    <probability>0.5</probability>
    <offset>0</offset>
  </sporadictask>


  <sporadictask>
    <id>14</id>
    <executiontime>3</executiontime>
    <criticaltime>4</criticaltime>
    <ucfirmrt/>
    <uamean/>
    <priority>1</priority>
    <minperiod>4</minperiod>
    <seed>0x3e8</seed>
    <probability>0.5</probability>
    <offset>0</offset>
  </sporadictask>


  <sporadictask>
    <id>15</id>
    <executiontime>3</executiontime>
    <criticaltime>16</criticaltime>
    <ucfirmrt/>
    <uamean/>
    <priority>1</priority>
    <minperiod>16</minperiod>
    <seed>0x3e8</seed>
    <probability>0.5</probability>
    <offset>0</offset>
  </sporadictask>

</taskset>

=== jiankangren/tms-sim/tasksets/tasksetTEST.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--Hier kommen die Tasks-->
<taskset xmlns="http://www.tmsxmlns.com" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.tmsxmlns.com taskset.xsd">

  <periodictask>
    <id>1</id>
    <executiontime>2</executiontime>
    <criticaltime>12</criticaltime>
    <ucfirmrt/>
    <uaexp>
      <weight>0.5</weight>
    </uaexp>
    <priority>0</priority>
    <period>12</period>
    <offset>0</offset>
  </periodictask>


  <periodictask>
    <id>2</id>
    <executiontime>2</executiontime>
    <criticaltime>12</criticaltime>
    <ucfirmrt/>
    <uaexp>
      <weight>0.5</weight>
    </uaexp>
    <priority>2</priority>
    <period>12</period>
    <offset>0</offset>
  </periodictask>


  <periodictask>
    <id>3</id>
    <executiontime>2</executiontime>
    <criticaltime>12</criticaltime>
    <ucfirmrt/>
    <uaexp>
      <weight>0.5</weight>
    </uaexp>
    <priority>4</priority>
    <period>12</period>
    <offset>0</offset>
  </periodictask>


  <sporadictask>
    <id>11</id>
    <executiontime>1</executiontime>
    <criticaltime>5</criticaltime>
    <ucfirmrt/>
    <uaexp>
      <weight>0.5</weight>
    </uaexp>
    <priority>1</priority>
    <minperiod>-1</minperiod>
    <seed>0xcafe600d</seed>
    <probability>0.33</probability>
    <offset>0</offset>
  </sporadictask>


  <sporadictask>
    <id>12</id>
    <executiontime>1</executiontime>
    <criticaltime>5</criticaltime>
    <ucfirmrt/>
    <uaexp>
      <weight>0.5</weight>
    </uaexp>
    <priority>1</priority>
    <minperiod>-1</minperiod>
    <seed>0xcafebad</seed>
    <probability>0.33</probability>
    <offset>0</offset>
  </sporadictask>


  <sporadictask>
    <id>13</id>
    <executiontime>1</executiontime>
    <criticaltime>5</criticaltime>
    <ucfirmrt/>
    <uaexp>
      <weight>0.5</weight>
    </uaexp>
    <priority>1</priority>
    <minperiod>-1</minperiod>
    <seed>0xcafebad0</seed>
    <probability>0.33</probability>
    <offset>0</offset>
  </sporadictask>

</taskset>

=== jiankangren/tms-sim/tasksets/taskset_demo.xml
<?xml version="1.0"?>

<taskset
  xmlns="http://www.tmsxmlns.com"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://www.tmsxmlns.com taskset.xsd">

  <periodictask>
    <id>1</id>
    <executiontime>12</executiontime>
    <criticaltime>2</criticaltime>
    <ucfirmrt></ucfirmrt>
    <uaexp>
    	<weight>0.5</weight>
    </uaexp>
    <priority>1</priority>
    <period>12</period>
    <offset>0</offset>
  </periodictask>
  
  <periodictask>
    <id>2</id>
    <executiontime>12</executiontime>
    <criticaltime>2</criticaltime>
    <ucfirmrt></ucfirmrt>
   	<uaexp>
		<weight>0.5</weight>
    </uaexp>
    <priority>1</priority>
    <period>12</period>
    <offset>2</offset>
  </periodictask>
  
  <periodictask>
    <id>3</id>
    <executiontime>12</executiontime>
    <criticaltime>2</criticaltime>
    <ucfirmrt></ucfirmrt>
    <uaexp>
		<weight>0.5</weight>
    </uaexp>
    <priority>1</priority>
    <period>12</period>
    <offset>4</offset>
  </periodictask>

  <sporadictask>
    <id>11</id>
    <executiontime>1</executiontime>
    <criticaltime>5</criticaltime>
    <ucfirmrt></ucfirmrt>
    <uaexp>
		<weight>0.5</weight>
    </uaexp>
    <priority>1</priority>
    <minperiod>5</minperiod>
    <seed>0xcafe600d</seed>
    <probability>0.33</probability>
    <offset>0</offset>
    
  </sporadictask>

  <sporadictask>
    <id>12</id>
    <executiontime>1</executiontime>
    <criticaltime>5</criticaltime>
    <ucfirmrt></ucfirmrt>
    <uaexp>
		<weight>0.5</weight>
    </uaexp>
    <priority>1</priority>
    <minperiod>5</minperiod>
    <seed>0x0cafebad</seed>
    <probability>0.33</probability>
    <offset>0</offset>
    
  </sporadictask>

  <sporadictask>
    <id>13</id>
    <executiontime>1</executiontime>
    <criticaltime>5</criticaltime>
    <ucfirmrt></ucfirmrt>
    <uaexp>
		<weight>0.5</weight>
    </uaexp>
    <priority>1</priority>
    <minperiod>5</minperiod>
    <seed>0xcafebad0</seed>
    <probability>0.33</probability>
    <offset>0</offset>
    
  </sporadictask>
  
  <mkftask>
    <id>14</id>
    <executiontime>1</executiontime>
    <criticaltime>5</criticaltime>
    <ucfirmrt></ucfirmrt>
    <uaexp>
		<weight>0.5</weight>
    </uaexp>
    <priority>1</priority>
    <period>5</period>
    <m>9</m>
    <k>6</k>
  </mkftask>
  
  <sporadicperiodictask>
    <id>15</id>
    <executiontime>12</executiontime>
    <criticaltime>2</criticaltime>
    <ucfirmrt></ucfirmrt>
    <uaexp>
		<weight>0.5</weight>
    </uaexp>
    <priority>1</priority>
    <period>12</period>
    <offset>4</offset>
    <seed>0xcafebad0</seed>
    <probability>0.33</probability>
  </sporadicperiodictask>

</taskset>

=== jiankangren/tms-sim/tasksets/taskset-mk.xml
<?xml version="1.0"?>

<!--

(m,k) taskset from Ramanathan 1999
C1 = 1, T1 = 3, m1 = 1, k1 = 1
C2 = 2, T2 = 4, m2 = 2, k2 = 3
C3 = 3, T3 = 12, m3 = 3, k3 = 5

-->

<taskset
  xmlns="http://www.tmsxmlns.com"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://www.tmsxmlns.com taskset.xsd">

  <mkftask>
    <id>1</id>
    <executiontime>1</executiontime>
    <criticaltime>3</criticaltime>
    <ucfirmrt></ucfirmrt>
    <uaexp>
    	<weight>0.5</weight>
    </uaexp>
    <priority>0</priority>
    <period>3</period>
    <offset>0</offset>
    <m>1</m>
    <k>1</k>
  </mkftask>
  
  <mkftask>
    <id>2</id>
    <executiontime>2</executiontime>
    <criticaltime>4</criticaltime>
    <ucfirmrt></ucfirmrt>
    <uaexp>
    	<weight>0.5</weight>
    </uaexp>
    <priority>1</priority>
    <period>4</period>
    <offset>0</offset>
    <m>2</m>
    <k>3</k>
  </mkftask>
  
  <mkftask>
    <id>3</id>
    <executiontime>3</executiontime>
    <criticaltime>12</criticaltime>
    <ucfirmrt></ucfirmrt>
    <uaexp>
    	<weight>0.5</weight>
    </uaexp>
    <priority>2</priority>
    <period>12</period>
    <offset>0</offset>
    <m>3</m>
    <k>5</k>
  </mkftask>


</taskset>
